language: node_js
node_js:
  - 'lts/*'

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

before_install:
  - yarn install
  - bin/retrieve-documentation

script:
  - yarn lint
  - yarn gatsby build
