import "styles/common.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen w-full light">
      <body className="bg-white dark:bg-blue-black">{children}</body>
    </html>
  );
}
