name: CD

on:
  workflow_dispatch: ~
  push:
  pull_request: ~

# Do not use concurrency to prevent simultaneous helm deployments
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      tags: |
        type=ref,event=pr,prefix=pr-,priority=1000
        type=edge,branch=$repo.default_branch,priority=900
        type=raw,value=latest,enable={{is_default_branch}},priority=900
      push: ${{ github.event_name != 'pull_request' }}
      gke-cluster: api-platform-demo
      gke-zone: europe-west1-c
    secrets:
      gke-credentials: ${{ secrets.GKE_SA_KEY }}
      gke-project: ${{ secrets.GKE_PROJECT }}
      gh-key: ${{ secrets.GH_KEY }}

  deploy:
    name: Deploy
    needs: [ build ]
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      docker-images-version: ${{ github.sha }}
      gke-cluster: api-platform-demo
      gke-zone: europe-west1-c
    secrets:
      gke-credentials: ${{ secrets.GKE_SA_KEY }}
      gke-project: ${{ secrets.GKE_PROJECT }}
      gh-key: ${{ secrets.GH_KEY }}
      # cloudflare-api-token: ${{ secrets.CF_API_TOKEN }}
      # cloudflare-zone-id: ${{ secrets.CF_ZONE_ID }}
